AllCops:
  Exclude:
    - 'Gemfile'
    - 'vendor/**/*'
    - eat_your_vegetables.gemspec
    - spec/spec_helper.rb
    - lib/eat_your_vegetables/tools/base.rb
    - lib/eat_your_vegetables/tools/rubocop.rb
    - lib/eat_your_vegetables/ambition.rb
    - lib/eat_your_vegetables.rb

Style/Documentation:
  Enabled: true
  Exclude:

Style/DocumentationMethod:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 75

Metrics/ClassLength:
  Max: 1000

Metrics/AbcSize:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 30

Metrics/ParameterLists:
  Max: 10

StringLiterals:
  EnforcedStyle: single_quotes

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SignalException:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/Next:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "**/*_factory.rb"
    - "config/initializers/*.rb"

Layout/IndentHash:
  EnforcedStyle: consistent

Style/MultilineBlockChain:
  Enabled: false
